### ISSUE TITLE
Please provide me with an activation key

### ISSUE THREAD

**Issue by devalian** [Azure/azurestack-uptime-monitor#32]
To receive an activation key for the connected version you need Azure Stack operator permissions to an Azure Stack multinode integrated solution.

Hi, im the managed services for a production multinode azure stack, but i have not gotten approval to proceed deployment. can i request activation key for ASDK deployment and testing first?

Thanks.

**Comment by marcvaneijk** [comment]
Hi @devalian,
Thank you for your interest in the Azure Stack uptime monitor solution.
Please sent the name of your company and your business email address to ```azs-uptime-monitor at microsoft.com``` and I will send the activation key there.

**Comment by devalian** [comment]
Thanks Marc. I had email in the request. Cheers!

**Comment by marcvaneijk** [comment]
Thanks for sending your business details @devalian 
I've provided an installation key on your business email.
