### ISSUE TITLE
Please provide me with an activation key

### ISSUE THREAD

**Issue by kent2004** [Azure/azurestack-uptime-monitor#41]
To receive an activation key for the connected version you need Azure Stack operator permissions to an Azure Stack multinode integrated solution.

Hello, I'm a cloud admin of Azure Stack. Please provide me activation key

**Comment by marcvaneijk** [comment]
Hi @kent2004 

Thank you for your interest in the Azure Stack uptime monitor solution.
Please sent the name of your company and your business email address to ```azs-uptime-monitor at microsoft.com``` and I will send the activation key there.

**Comment by marcvaneijk** [comment]
provided the key on the business email address
